name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Build
      - run: npm ci
      - run: npm run build
      # Deploy
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --verbose --compress --delete --delete-excluded --exclude '.DS_Store' --copy-links . deploy@weblind.ru:/opt/sites/weblind.ru/public/
        working-directory: ./dist
